<?php

/**
 * AgendasRegionais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AgendasRegionais extends BaseAgendasRegionais
{
	function recuperarCampos($agendasregionais, $post, $action=null)
    {
        if ($action == 'editar')
            $agendasregionais->id = $post['id'];

		$agendasregionais->data_agenda = $post['data_agenda'];
		$agendasregionais->local       = $post['local'];
		$agendasregionais->titulo      = $post['titulo'];		
        $agendasregionais->descricao   = $post['descricao'];
                
        return $agendasregionais;
    }
    
    function validar ($agendasregionais, $action=null)
    {
        $erro = array();
        
		if (empty($agendasregionais->data_agenda)) $erro[] = 'data_agenda_erro'; 
		if (empty($agendasregionais->local))       $erro[] = 'local_erro'; 
		if (empty($agendasregionais->titulo))      $erro[] = 'titulo_erro';				
        
        return $erro;
    }

}