<?php

/**
 * AgendasGerais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AgendasGerais extends BaseAgendasGerais
{
	function recuperarCampos($agendasgerais, $post, $action=null)
    {
        if ($action == 'editar')
            $agendasgerais->id = $post['id'];

		$agendasgerais->data_agenda = $post['data_agenda'];
		$agendasgerais->local       = $post['local'];
		$agendasgerais->titulo      = $post['titulo'];		
        $agendasgerais->descricao   = $post['descricao'];
                
        return $agendasgerais;
    }
    
    function validar ($agendasgerais, $action=null)
    {
        $erro = array();
        
		if (empty($agendasgerais->data_agenda)) $erro[] = 'data_agenda_erro'; 
		if (empty($agendasgerais->local))       $erro[] = 'local_erro'; 
		if (empty($agendasgerais->titulo))      $erro[] = 'titulo_erro';				
        
        return $erro;
    }
}