<?php

/**
 * AtasDirgeral
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AtasDirgeral extends BaseAtasDirgeral
{
	function recuperarCampos($atasdirgeral, $post, $action=null)
    {
        if ($action == 'editar')
            $atasdirgeral->id = $post['id'];

		$atasdirgeral->titulo    = $post['titulo'];
		$atasdirgeral->numero    = $post['numero'];
		$atasdirgeral->data_ata  = $post['data_ata'];
        $atasdirgeral->descricao = $post['descricao'];
                
        return $atasdirgeral;
    }
    
    function validar ($atasdirgeral, $action=null)
    {
        $erro = array();
        
		if (empty($atasdirgeral->titulo))    $erro[] = 'titulo_erro'; 
		if (empty($atasdirgeral->numero))    $erro[] = 'numero_erro'; 
		if (empty($atasdirgeral->data_ata))  $erro[] = 'data_ata_erro'; 
		if (empty($atasdirgeral->descricao)) $erro[] = 'descricao_erro';
        
        return $erro;
    }
}