<?php

/**
 * AtasRegionais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AtasRegionais extends BaseAtasRegionais
{
	function recuperarCampos($atasregionais, $post, $action=null)
    {
        if ($action == 'editar')
            $atasregionais->id = $post['id'];

		$atasregionais->titulo    = $post['titulo'];
		$atasregionais->numero    = $post['numero'];
		$atasregionais->data_ata  = $post['data_ata'];
        $atasregionais->descricao = $post['descricao'];
                
        return $atasregionais;
    }
    
    function validar ($atasregionais, $action=null)
    {
        $erro = array();
        
		if (empty($atasregionais->titulo))    $erro[] = 'titulo_erro'; 
		if (empty($atasregionais->numero))    $erro[] = 'numero_erro'; 
		if (empty($atasregionais->data_ata))  $erro[] = 'data_ata_erro'; 
		if (empty($atasregionais->descricao)) $erro[] = 'descricao_erro';
        
        return $erro;
    }
}