<?php

/**
 * MembrosRegionais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MembrosRegionais extends BaseMembrosRegionais
{
	function recuperarCampos($membrosregionais, $post, $action=null)
    {
        if ($action == 'editar')
            $membrosregionais->id = $post['id'];

		$membrosregionais->igreja_id     = $post['igreja_id'];
		$membrosregionais->nome          = $post['nome'];
		$membrosregionais->funcao        = $post['funcao'];		
        $membrosregionais->telefone      = $post['telefone'];
		$membrosregionais->email         = $post['email'];
		$membrosregionais->inicio_gestao = $post['inicio_gestao'];
		$membrosregionais->final_gestao  = $post['final_gestao'];
                
        return $membrosregionais;
    }
    
    function validar ($membrosregionais, $action=null)
    {
        $erro = array();
        
		if (empty($membrosregionais->igreja_id))     $erro[] = 'igreja_id_erro'; 
		if (empty($membrosregionais->nome))          $erro[] = 'nome_erro'; 
		if (empty($membrosregionais->funcao))        $erro[] = 'funcao_erro';				
		if (empty($membrosregionais->inicio_gestao)) $erro[] = 'inicio_gestao_erro';
	        
        return $erro;
    }

}