<?php

/**
 * MembrosDirgeral
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MembrosDirgeral extends BaseMembrosDirgeral
{
	function recuperarCampos($membrosdirgeral, $post, $action=null)
    {
        if ($action == 'editar')
            $membrosdirgeral->id = $post['id'];

		$membrosdirgeral->igreja_id     = $post['igreja_id'];
		$membrosdirgeral->nome          = $post['nome'];
		$membrosdirgeral->funcao        = $post['funcao'];		
        $membrosdirgeral->telefone      = $post['telefone'];
		$membrosdirgeral->email         = $post['email'];
		$membrosdirgeral->inicio_gestao = $post['inicio_gestao'];
		$membrosdirgeral->final_gestao  = $post['final_gestao'];
                
        return $membrosdirgeral;
    }
    
    function validar ($membrosdirgeral, $action=null)
    {
        $erro = array();
        
		if (empty($membrosdirgeral->igreja_id))     $erro[] = 'igreja_id_erro'; 
		if (empty($membrosdirgeral->nome))          $erro[] = 'nome_erro'; 
		if (empty($membrosdirgeral->funcao))        $erro[] = 'funcao_erro';				
		if (empty($membrosdirgeral->inicio_gestao)) $erro[] = 'inicio_gestao_erro';
	        
        return $erro;
    }
}