<?php

/**
 * Menus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Menus extends BaseMenus
{
	function recuperarCampos($menus, $post, $action=null)
	{
		if($action == 'editar')
			$menus->id = (int) $post['id'];
		
		$menus->posicao = (int) $post['posicao'];
		$menus->nome = trim($post['nome']);
		$menus->status = (int) $post['status'];
		
		return $menus;
	}
	
	function validar($menus, $action=null)
	{
		$erro = array();
		
		if(empty($menus->nome)) $erro[] = 'nome_erro';
		
		return $erro;
	}
}