<?php

/**
 * Regionais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Regionais extends BaseRegionais
{

    function recuperarCampos($regionais, $post, $action=null)
    {
        if ($action == 'editar')
            $regionais->id = $post['id'];
        
		$regionais->codigo    = $post['codigo'];
        $regionais->nome      = $post['nome'];
        $regionais->descricao = $post['descricao'];
        $regionais->status    = $post['status'];
        
        return $regionais;
    }
    
    function validar ($regionais, $action=null)
    {
        $erro = array();
        
		if (empty($regionais->codigo))  $erro[] = 'codigo_erro'; 
        if (empty($regionais->nome))  $erro[] = 'nome_erro'; 
        
        return $erro;
    }
	
    public function setUp()
    {		
        $this->hasMany('Igrejas', array(
                'local' => 'id',
                'foreign' => 'regional_id'
            )
        );
    }
}
