<?php

/**
 * Tabelas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tabelas extends BaseTabelas
{
	function recuperarCampos($tabelas, $post, $action=null)
	{
		if($action == 'editar')
			$tabelas->id = (int) $post['id'];
		
		$tabelas->menu_id = (int) $post['menu_id'];
		$tabelas->nome = trim($post['nome']);
		$tabelas->tabela = trim($post['tabela']);
		$tabelas->status = (int) $post['status'];
		
		return $tabelas;
	}
	
	function validar($tabelas, $action=null)
	{
		$erro = array();
		
		if(empty($tabelas->menu_id)) $erro[] = 'menu_id_erro';
		if(empty($tabelas->nome)) $erro[] = 'nome_erro';
		if(empty($tabelas->tabela)) $erro[] = 'tabela_erro';
		
		return $erro;
	}
	
    public function setUp()
    {
        parent::setUp();

        $this->hasMany('Usuarios', array(
                'local' => 'tabela_id',
                'foreign' => 'usuario_id',
                'refClass' => 'UsuariosTabelas'
            )
        );
		
        $this->hasMany('Tipos', array(
                'local' => 'tabela_id',
                'foreign' => 'tipo_id',
                'refClass' => 'TabelasTipos'
            )
        );
    }
}