<?php

/**
 * Tipos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tipos extends BaseTipos
{
	function recuperarCampos($tipos, $post, $action=null)
	{
		if($action == 'editar')
			$tipos->id = $post['id'];
		
		$tipos->nome = $post['nome'];		
		$tipos->status = $post['status'];
		
		return $tipos;
	}
	
	function validar($tipos, $action=null)
	{
		$erro = array();
		
		if(empty($tipos->nome)) $erro[] = 'nome_erro';
		
		return $erro;
	}
	
    public function setUp()
    {
        parent::setUp();
		
        $this->hasMany('Tipos', array(
                'local' => 'tipo_id',
                'foreign' => 'tabela_id',
                'refClass' => 'TabelasTipos'
            )
        );
    }
}