<?php

/**
 * Usuarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usuarios extends BaseUsuarios
{
	function recuperarCampos($usuarios, $post, $action=null)
	{
		if($action == 'editar')
			$usuarios->id = (int) $post['id'];
		
		$usuarios->tipo_id = (int) $post['tipo_id'];
		$usuarios->regional_id = (int) $post['regional_id'];
		$usuarios->nome = trim($post['nome']);
		$usuarios->email = trim($post['email']);
		$usuarios->telefone = trim($post['telefone']);
		$usuarios->celular = trim($post['celular']);
		$usuarios->login = trim($post['login']);
		$usuarios->status = (int) $post['status'];
		
		# não obriga o usuario a mudar a senha ao alterar o perfil
		if(!empty($post['senha']))
		{
			$usuarios->senha = trim($post['senha']);
			
			# criptografar a senha
			$usuarios->senha = geraSenhaAdmin($usuarios->senha);
		}
		
		return $usuarios;
	}
	
	function validar($usuarios, $action=null)
	{
		$erro = array();
		
		if(empty($usuarios->tipo_id)) $erro[] = 'tipo_id_erro';
		if(empty($usuarios->nome)) $erro[] = 'nome_erro';
		if(empty($usuarios->email)) $erro[] = 'email_erro';
		if(empty($usuarios->login)) $erro[] = 'login_erro';
		
		# valida se o tipo de usuario for Regional
		if($usuarios->tipo_id == 3)
		{
			if(empty($usuarios->regional_id)) $erro[] = 'regional_id_erro';
		}
		
		# so valida se tivercriando um novo registro
		if(empty($usuarios->id))
		{
			if(empty($usuarios->senha)) $erro[] = 'senha_erro';
		}

		return $erro;
	}
	
    public function setUp()
    {
        parent::setUp();

        $this->hasMany('Tabelas', array(
                'local' => 'usuario_id',
                'foreign' => 'tabela_id',
                'refClass' => 'UsuariosTabelas'
            )
        );
    }
}